### ISSUE TITLE
allow to see running command and kill it

### ISSUE THREAD

**Issue by flying-sheep** [hirohisa/atom-project-runner#3]
when the running of the project involves e.g. a server, my use case is like this:

1. use user key bindings to allow ctrl+r to work on non-OSX systems *grrr*
2. hit ctrl+r → nothing visible happens
3. hit it again → error: address in use
4. use a task manager to kill server and start it from a terminal instead

**Comment by hirohisa** [comment]
> process kill

Fix by https://github.com/hirohisa/atom-project-runner/pull/11
